package com.searchteam.bot.pipeline;

public enum PipelineEnum {
    NONE, START, CREATE_QUESTIONNAIRE, CREATE_TEAM, FIND_TEAM,
    PROJECT_CHOICE, COMPLETED_QUESTIONNAIRE, ACCOUNT,
    EDIT_QUESTIONNAIRE, TEAM_CHOICE, SELECTED_TEAM,
    SUBMITTED_QUESTIONNAIRE
}
