version: '3.8'

services:
  db:
    image: postgres:16-alpine
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YQgD1d
      POSTGRES_DB: SearchTeam
