version: '3.8'

name: bot_search_team
services:
  db:
    image: postgres:16-alpine
    ports:
      - "9000:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YQgD1d
      POSTGRES_DB: SearchTeam
