spring:
  application:
    name: bot
  docker:
    compose:
      skip:
        in-tests: true
      lifecycle-management: start_and_stop
      enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  sql:
    init:
      mode: never
bot:
  token: 6912900868:AAGR5hplJXwgqnccNBzoi7-zNkyIoTPLVnM
  name: SearchTeamPolytech
event:
  name: ${NAME_EVENT}
  password: ${EVENT_PASSWORD}
  count-people: ${COUNT_PEOPLE}
  projects:
    url: ${PROJECTS_URL}